{
 "title": "Nakama client Authentication Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Connected Players",
   "type": "timeseries",
   "description": "Total active user sessions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nakama_presences", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "timeseries",
   "description": "How many DB connections Nakama is using",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nakama_db_total_open_conns", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total request",
   "type": "timeseries",
   "description": "Total rate of all requests handled by Nakama",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(nakama_overall_request_count[$__rate_interval])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Avg Email Login Latency (ms)",
   "type": "timeseries",
   "description": "Average response time for email logins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(nakama_AuthenticateEmail_latency_ms_sum[$__rate_interval]) / rate(nakama_AuthenticateEmail_latency_ms_count[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Login Rate (Email Authentications/sec)",
   "type": "timeseries",
   "description": "Tracks the rate of email-based user logins to the Nakama server using Prometheus rate() over 5 minutes.\nHigher values indicate more active login traffic.\n",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(nakama_AuthenticateEmail_count[$__rate_interval])",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}